Fix main page
AtomST/sultan-web pull request #11
Opened 2024-11-13 16:33 UTC by AtomST

2024-11-14 06:21 UTC, olya-yevsieienko requested changes
Вы хорошо поработали, нужно внести немного правок 👍

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/LocalSwitcher/local-switcher.js
> +  const getNextLocale = (locale) => (locale === LOCALES.RU ? LOCALES.EN : LOCALES.RU);
Это лучше вынести в core проекта, может пригодиться в других местах.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/LocalSwitcher/local-switcher.js
> +        {currentLocale === LOCALES.RU ? 'English' : 'Русский'}
Нужно заменить на i18n.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/ProductCard/ProductCard.js
> +                    {t("productName") === "ru" ? el.nameRu : el.nameEn}</div>
Вот этот код дублируется, стоит его вынести в отдельную функцию.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/UI/ButtonUI/ButtonUI.jsx
> +            disabled={disabled}
Это полностью скопированный код из моего примера.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/UI/mobileButton/index.js
> +export { default } from './mobileButton.js';
Пустая строка в конце файла.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/UI/mobileButton/mobileButton.js
> +  const displayedIcon = isClicked && iconClick ? iconClick : icon;
Что такое iconClick?

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/navMenu.js
> +    }));
Убрать это. MENU_ITEMS должен быть сразу наполнен всем, что нужно.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/constants.js
> +];
Добавить сюда title.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/componentsStyles.module.scss
> +    width: 39px;
Переписать с использованием &.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/mobileMenu/mobileMenu.js
> +        <div className={styles.contactInformation}>
Форматирование.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/mobileMenu/mobileMenu.js
> +                            <span>{t('salesDep')}</span>
Везде проверить форматирование.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/mobileMenu/mobileMenu.js
> +                            <span>+7 (777) 490-00-91</span>
Это должна быть ссылка с телефоном.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/mobileMenu/mobileMenu.js
> +            </div>
Форматирование.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/mobileMenu/mobileMenu.module.scss
> +    padding: 20px 15px 32px 13px;
Отступы внутренние и внешние, ширина, высота должны быть числами, которые делятся на 4 без остатка. Проверить везде.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/vars.scss
> +$search-color-hover: #EDEDED7F;
Это явно цвет search-color с какой-то прозрачность.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/vars.scss
> +$menu-overlay-color: #0000007F;
Это тоже какой-то цвет с прозрачностью.

2024-11-14 06:21 UTC, olya-yevsieienko commented on src/app/[locale]/vars.scss
> +$font-inter: 'Inter', sans-serif;
Пустая строка в конце файла.

2024-11-17 17:56 UTC, nikolaichaikin commented on src/app/[locale]/components/UI/mobileButton/mobileButton.js
> +  const displayedIcon = isClicked && iconClick ? iconClick : icon;
Это иконка, которая отображается, если меню открыто 
![Screenshot_1](https://github.com/user-attachments/assets/618573cd-2766-43e8-b656-18147b6db013)

2024-11-19 14:21 UTC, olya-yevsieienko approved these changes
Нужно внести мелкие правки и сливать ветку.

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/BannerPromo.js
> +    return(
```suggestion
"use client";

import { useTranslations } from "next-intl";

export const elemPlus = <span className="banner-footer-plus">+</span>;

export const PromoContent = () => {
    const t = useTranslations("Banner");
   
    return(
```

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/CategoriesSection/CategoriesSection.jsx
> +                setItems(data.items);
А зачем тут отдельные стейты? Почему нельзя использовать один и из него доставать данные?

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/FeaturedProducts/FeaturedProducts.js
> +    return (
Тут, кажется, нет пустой строки перед return.

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/LocalSwitcher/local-switcher.js
> +  };
```suggestion
    const flagStyle = isHovered ? { filter: 'brightness(0.9)' } : {};
    
    if (locale === LOCALES.RU) {
      return (
        <Image src='/icon/header-flag-gb.svg' 
          width={36} 
          height={36} 
          style={flagStyle} 
          alt='british flag'
        />
      );
    }
    
    return (
      <Image src='/icon/header-flag-ru.svg' 
        width={36} 
        height={36} 
        style={flagStyle} 
        alt='russian flag'
      />
    );
  };
```

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/LocalSwitcher/local-switcher.js
> +  const t = useTranslations('LocalSwitcher');
Поднять эту строчку вверх к хукам.

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/LocalSwitcher/localSwitcher.module.scss
> +@import '../../mixins.scss';
@import "vars";
@import "mixins";

По-разному импорты написаны в файлах, нужно привести к одному виду.

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/UI/Icons/Icons.jsx
> +    return <span className={iconClasses} />;
```suggestion
    const iconClasses = `ui-icon ui-icon--${name} ui-icon--${color}`;
    
    return <span className={iconClasses} />;
```

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/componentsStyles.module.scss
> +
По-разному импорты написаны в файлах, нужно привести к одному виду.

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/mobileMenu/mobileMenu.js
> +  return (
```suggestion
  const t = useTranslations('Header');
  
  return (
```

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/core/hooks/useNextLocale.js
> +  return getNextLocale;
```suggestion
  const getNextLocale = () => (currentLocale === LOCALES.RU ? LOCALES.EN : LOCALES.RU);
  
  return getNextLocale;
```

2024-11-19 14:21 UTC, olya-yevsieienko commented on src/app/[locale]/vars.scss
> +$text-color-search: #5c6370;
Это тоже лучше написать в upperCase.

2024-11-20 08:21 UTC, merged