Develop to master(feat: Header, ProductCards, Sliders, Map, Footer)
AtomST/sultan-web pull request #7
Opened 2024-10-31 19:01 UTC by AtomST

2024-11-02 22:13 UTC, GrozaMorei commented on src/app/[locale]/components/Banner/Banner.js
> +        <div className="banner">
Не знаю, правильно или нет, но я использую тег section, а не просто div

2024-11-03 10:20 UTC, GrozaMorei commented on src/app/[locale]/components/Banner/Banner.js
> +        <div className="banner">
Не знаю, насколько правильно, но я бы использовал тег section

2024-11-03 10:30 UTC, GrozaMorei commented on src/app/[locale]/components/Banner/Banner.js
> +        <div className="banner-footer-mobile" >
Как я понимаю, это отдельная разметка под мобильную версию, я бы не стал адаптив реализовывать в разметке
(Личное мнение, могу ошибаться, опыта мало)

2024-11-03 10:34 UTC, GrozaMorei commented on src/app/[locale]/components/Banner/Banner.scss
> +        background: linear-gradient(89.86deg, #8A94AB 0.13%, rgba(138, 148, 171, 0) 99.89%);
Очень странно выглядят подобные значения. Я понимаю еще границу цвета и его прозрачность указать с такой точность, но поворот в 89.99.. зачем?
(Личное мнение, могу ошибаться, опыта мало)

2024-11-03 10:36 UTC, GrozaMorei commented on src/app/[locale]/components/Banner/Banner.scss
> +        height: 692px;
Снова придерусь, я бы округлил до 690px)
(Личное мнение, могу ошибаться, опыта мало)

2024-11-03 10:43 UTC, GrozaMorei commented on src/app/[locale]/components/Banner/Banner.scss
> +            background-color: var(--button-color);
Данный цвет в макете используется не только для кнопок, но и заголовков. Я бы назвал его акцентным цветом
(Личное мнение, могу ошибаться, опыта мало)

2024-11-03 10:45 UTC, GrozaMorei commented on src/app/[locale]/components/ButtonTemplate/ButtonTemplate.js
> +
Не знаю, можно так сделать так или нет, но я бы хотел сделать так, чтобы кнопке передавалась также либо ссылка / скрипт, который бы она исполняла
(Личное мнение, могу ошибаться, опыта мало)

2024-11-03 10:55 UTC, GrozaMorei commented on src/app/[locale]/components/ContactMapSection/ContactMapSection.js
> +                <div className="contact-info-container">
Я бы использовал здесь список ul
(Личное мнение, могу ошибаться, опыта мало)

2024-11-03 11:00 UTC, GrozaMorei commented on src/app/[locale]/components/Footer/Categories.js
> +                    <a href={item.link}>{item.name}</a>
Насколько мне известно, в реакте предпочтительнее использовать специальный тег для ссылок
(Личное мнение, могу ошибаться, опыта мало)

2024-11-03 11:02 UTC, GrozaMorei commented on src/app/[locale]/components/Footer/CompanyInfo.js
> +                <button type="submit" className="subscribe-button">
А почему здесь не subscribe-form-button?
(Личное мнение, могу ошибаться, опыта мало)

2024-11-03 11:08 UTC, GrozaMorei commented on src/app/[locale]/components/Footer/Footer.css
> +.subscribe-button {
Придираюсь. Слишком много стилей. В таком случае я бы разбил их на смысловые блоки с разделением пустой строкой
(Личное мнение, могу ошибаться, опыта мало)

2024-11-03 11:10 UTC, GrozaMorei commented on src/app/[locale]/components/Footer/PriceList.js
> +                                <path
Не совсем понимаю, что это
(Личное мнение, могу ошибаться, опыта мало)

2024-11-03 11:12 UTC, GrozaMorei commented on src/app/[locale]/components/ProductCard/ProductCard.css
> +    box-shadow: 0px 14px 39px -11px #0000000F;
Отрицательное четвертое значение?
(Личное мнение, могу ошибаться, опыта мало)

2024-11-07 14:38 UTC, GrozaMorei commented on messages/ru.json
> +        "popular": "ПОПУЛЯРНОЕ",
Я бы не стал писать в json в большом регистре, так как это обычно делается в css

2024-11-07 14:54 UTC, GrozaMorei commented on public/data/productDTOs_main.json
> +        "width":92,
Допустим это json файл с информацией о товарах. Не совсем понимаю, почему здесь прописываются высота и ширина изображений товара, ведь сами изображения помещаются в контейнер в карточке, который и должен регулировать эти параметры, а каждое изображение может иметь свой размер и передавать ее потом в виде параметров в разметку не вижу никакого смысла
(Это мое личное мнение, которое может быть не верным в связи с малым опытом)

2024-11-07 15:13 UTC, GrozaMorei commented on src/app/[locale]/components/header/componentsStyles.module.css
> +    width: 18.35px;
Я понимаю, что так было в дизайне, но я бы не стал использовать такую точность
(Это мое личное мнение, которое может быть не верным в связи с малым опытом)

2024-11-07 15:16 UTC, GrozaMorei commented on src/app/[locale]/components/header/componentsStyles.module.css
> +    /* .menuItem:nth-child(2) {
Я думаю на этапе PR неиспользуемый код удаляется, либо (личный опыт) оставляется поясняющий комментарий к коду (для чего он и почему оставлен)
(Это мое личное мнение, которое может быть не верным в связи с малым опытом)

2024-11-07 15:21 UTC, GrozaMorei commented on src/app/[locale]/components/header/header.js
> +const icon1 = (
Не совсем понимаю, что это за переменная. Это svg представленная в виде кода? Зачем?)
(Это мое личное мнение, которое может быть не верным в связи с малым опытом)

2024-11-07 15:34 UTC, GrozaMorei commented on src/app/[locale]/components/header/mobileHeader/mobileMenu.module.css
> +  background-color: #ffff;
Цвета кстати говорили выносить в глобальные переменные
(Это мое личное мнение, которое может быть не верным в связи с малым опытом)

2024-11-07 15:36 UTC, GrozaMorei commented on src/app/[locale]/components/header/mobileHeader/mobileMenu.module.css
> +  bottom: -25px;
Насколько я знаю, при позиционировании необходимо использовать помимо вертикального положения еще и горизонтальное, даже если оно задано по умолчанию (bottom: -25px und right: 0 / left: 0)
(Это мое личное мнение, которое может быть не верным в связи с малым опытом)

2024-11-07 15:41 UTC, GrozaMorei commented on src/app/[locale]/globals.css
> +.page-main {
Комментарии считаю здесь излишними)
(Это мое личное мнение, которое может быть не верным в связи с малым опытом)

2024-11-07 15:52 UTC, GrozaMorei commented on src/app/[locale]/globals.css
> +        padding: 0 15px; /* Отступы для меньших экранов */
Для меньших экранов на 1440? Как я понимаю это в принципе отступы у страницы. Если да, то я бы вынес это из брейкпоинта
(Это мое личное мнение, которое может быть не верным в связи с малым опытом)

2024-11-08 03:51 UTC, olya-yevsieienko commented on messages/en.json
> +    },
Лучше не писать в верхнем регистре. Этот текст может использоваться где-то ещё.
А в этом конкретном случае задается нужный стиль кнопке.

2024-11-08 03:51 UTC, olya-yevsieienko commented on messages/en.json
> +}
Во всех файлах должна быть одна пустая строка в конце.

2024-11-08 03:51 UTC, olya-yevsieienko commented on public/data/productDTOs_main.json
> +        "width":92,
Я так понимаю, это для NextImage. 
Но замечание верное. Если эти данные лежат в json, предполагается, что данные приходят из админки, например. Скорее всего, в админке не будет полей, которые будут отвечать для ввод размеров для изображения.  Так что эту информацию лучше убрать. 
Насчет alt. Он тоже, скорее всего, приходить с бэка не будет. 
Можно написать функцию, которая будет проверять язык и в зависимости от этого подскатавлять nameRu или nameEn.

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.js
> +    return (
Везде соблюдаем форматирование.

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.js
> +import ButtonTemplate from "../ButtonTemplate/ButtonTemplate";
Везде соблюдаем порядок подключения импортов.

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.js
> +                    </div>
Форматирование.
Если атрибутов больше одного, то каждый располагается на новой строчке.
<ButtonTemplate
  width={39}
  height={39}
  text={"+"}
  className="btn-banner-plus"
/>

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.js
> +}
Лишние пустые строки.

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.scss
> +    .banner-blur {
Отлично, что подключили scss)
Теперь можно писать &-blur {}.

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.scss
> +        height: 692px;
Лучше верстать так, чтобы такие значения (ширина, высота) делились на 4. (если нет требования pixel perfect)

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.scss
> +        color: #FFFFFF;
Вынести в переменную.

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.scss
> +            line-height: 77px;
Можно напистаь просто 1.1.

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.scss
> +
Лишняя пустая строка.

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.scss
> +
В общем, проверить все файлы на наличие лишних пустых строк)

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.scss
> +                line-height: 21.78px;
Дробные значения лучше не писать.

2024-11-08 03:51 UTC, olya-yevsieienko commented on src/app/[locale]/components/Banner/Banner.scss
> +@media (max-width: 675px) {
Все брейкпоинты вынести в переменные. 
Media в scss предпочтительнее прописывать подобным образом. Так у вас есть возможность видеть сразу все стили, которые относятся к конкретному классу)
![image](https://github.com/user-attachments/assets/f19d0100-b771-43b7-9620-84a0cb80b37c)

2024-11-08 07:08 UTC, olya-yevsieienko requested changes
Хорошая работа, молодцы 👍

Проверьте, пожалуйста, форматирование, порядок подключения импортов и написания свойств во всех файлах.

2024-11-08 07:08 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/mobileHeader/mobileButton.js
> +const MobileButton = ({ customStyle = {}, icon = null, iconClick = null, onClick = null, href = null, isClick = null, text = null}) => {
Это должна быть всё та же отдельная кнопка)

2024-11-08 07:08 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/mobileHeader/mobileButton.js
> +  );
Лучше так не делать и разделять функционал. Если нужно, чтобы был переход по ссылке, по просто передайте это чреез onClick или оберните кнопку в Link.

```
    <Link href="/new-path">
      <Button>Перейти на новый путь</Button>
    </Link>
```

2024-11-08 07:08 UTC, olya-yevsieienko commented on src/app/[locale]/components/header/navMenu.js
> +    ];
ВЫнести в constants.js в папку с компонентом.

2024-11-10 12:28 UTC, AtomST commented on public/data/productDTOs_main.json
> +        "width":92,
Исправлено.

2024-11-10 13:59 UTC, AtomST commented on src/app/[locale]/components/ProductCard/ProductCard.js
> +}
Возможно чего-то не понимаю, но вложенные тернарники читаются неприятно, как их не форматируй, если не вкладывать, то нужно 2 раза проверять isLiquid, поэтому я вынес в функцию.
А ShowInfo это больше заготовка на будущее, т.к помимо "популярное" еще как минимум 4 варианта есть.
![image](https://github.com/user-attachments/assets/5204014a-f5c0-4ddf-8f42-4a9b99bd4617)
Такое все равно пишут в рендере компонента?

2024-11-11 06:05 UTC, AtomST commented on messages/en.json
> +    },
Исправлено.

2024-11-11 06:05 UTC, AtomST commented on messages/en.json
> +}
Исправлено.

2024-11-20 15:45 UTC, merged